---
- name: Attempting to purge old kernel packages
  become: true
  yum:
    disable_plugin: "{{ elrepo_disable_plugin|join(',') }}"
    disablerepo: "{{ elrepo_disablerepo|join(',') }}"
    enable_plugin: "{{ elrepo_enable_plugin|join(',') }}"
    enablerepo: "{{ elrepo_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: absent
  loop:
    - kernel-devel
    - kernel-tools
    - kernel-tools-libs
    - kernel-headers
  loop_control:
    label: "{{ item }}"

- name: Appending elrepo-kernel to elrepo_enablerepo list
  set_fact:
    elrepo_enablerepo: "{{ elrepo_enablerepo }} + [ 'elrepo-kernel' ]"
  when: "'elrepo-kernel' not in elrepo_enablerepo"

- name: Ensure that the elrepo kernel packages are installed
  become: true
  yum:
    disable_plugin: "{{ elrepo_disable_plugin|join(',') }}"
    disablerepo: "{{ elrepo_disablerepo|join(',') }}"
    enable_plugin: "{{ elrepo_enable_plugin|join(',') }}"
    enablerepo: "{{ elrepo_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  register: elrepo_kernel_installed
  loop:
    - "kernel-{{ elrepo_kernel_version }}"
    - "kernel-{{ elrepo_kernel_version }}-devel"
    - "kernel-{{ elrepo_kernel_version }}-headers"
  loop_control:
    label: "{{ item }}"

- name: Ensure that the kernel tools packages are installed
  become: true
  yum:
    disable_plugin: "{{ elrepo_disable_plugin|join(',') }}"
    disablerepo: "{{ elrepo_disablerepo|join(',') }}"
    enable_plugin: "{{ elrepo_enable_plugin|join(',') }}"
    enablerepo: "{{ elrepo_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  loop:
    - "kernel-{{ elrepo_kernel_version }}-tools"
    - "kernel-{{ elrepo_kernel_version }}-tools-libs"
  loop_control:
    label: "{{ item }}"
  when:
    - elrepo_dist == '7'
    - elrepo_kernel_installed is changed

- name: Attempting to set the default grub kernel for el6
  become: true
  lineinfile:
    dest: /boot/grub/grub.conf
    regexp: '^default='
    line: 'default=0'
  when:
    - elrepo_dist == '6'
    - elrepo_kernel_installed is changed

- name: Attempting to set the default grub kernel for el7
  become: true
  command: |
    /usr/sbin/grub2-set-default 0
  when:
    - elrepo_dist == '7'
    - elrepo_kernel_installed is changed

- name: Ensure that the required elrepo packages are installed
  become: true
  yum:
    disable_plugin: "{{ elrepo_disable_plugin|join(',') }}"
    disablerepo: "{{ elrepo_disablerepo|join(',') }}"
    enable_plugin: "{{ elrepo_enable_plugin|join(',') }}"
    enablerepo: "{{ elrepo_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  loop: "{{ elrepo_packages }}"
  loop_control:
    label: "{{ item }}"
  when:
    - elrepo_packages|length > 0
    - elrepo_yum is success
...
